server:
  port: 8190
  servlet:
    context-path: /contracts
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contracts
    jdbc-url: jdbc:postgresql://localhost:5432/contracts
    username: postgres
    password: postgres